CREATE TABLE IF NOT EXISTS "Farmers" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "phone" VARCHAR(255) UNIQUE NOT NULL,
  "name" VARCHAR(255),
  "language" VARCHAR(50) DEFAULT 'en',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Farms" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "land_size" FLOAT NOT NULL,
  "soil_type" VARCHAR(255) NOT NULL,
  "irrigation_source" VARCHAR(255),
  "district" VARCHAR(255) NOT NULL,
  "FarmerId" UUID REFERENCES "Farmers"("id") ON DELETE SET NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Crops" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "season" VARCHAR(255),
  "soil_suitability" TEXT[],
  "duration_days" INTEGER,
  "expected_yield" VARCHAR(255),
  "avg_profit_per_acre" FLOAT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
